apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department-service
  template:
    metadata:
      labels:
        app: department-service
    spec:
      containers:
        - name: department-service
          image: department-service:1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: department-service
spec:
  selector:
    app: department-service
  ports:
    - port: 8080
      targetPort: 8080
